module.exports = {
  'card_activateurl': '/pay/user/weixin_card_activateurl',
  'goods_cat': '/pay/mall/goods_cat',
  'goods': '/pay/mall/goods',
  'goods_detail': '/pay/mall/goods_detail',
  'slider': '/pay/cash/slider',
  'login': '/pay/cash/login',
  'order': '/pay/cash/order',
  'wxCode2Session': '/pay/mall/wxCode2Session',
  'pay_order': '/pay/mall/pay_order',
  'pay': '/pay/cash/pay',
  'refund': '/pay/cash/refund',
  'get_out_trade_no_mall': '/pay/mall/index',
  'get_out_trade_no_cash': '/pay/cash/index',
  'query': '/pay/cash/query',
  'check': '/pay/cash/check',
  'shortlink': '/home/url/create',
  'session': '/pay/weixin/session',
  'weixin_card_open': '/pay/user/weixin_card_open',
  'weixin_card_userinfo': '/pay/user/weixin_card_userinfo',
}